-- Maa Diaries Jewelry E-Commerce Supabase Schema Setup Script
-- Copy and paste this script into your Supabase SQL Editor and click RUN.

-- 1. Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) and grant all access for sandbox simplicity
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.categories FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.categories FOR DELETE USING (true);


-- 2. Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id text PRIMARY KEY,
    name text NOT NULL,
    description text,
    category text NOT NULL,
    subcategory text,
    price numeric NOT NULL,
    original_price numeric,
    discount numeric,
    image text,
    rating numeric DEFAULT 5.0,
    reviews_count integer DEFAULT 0,
    metal_options jsonb DEFAULT '[]'::jsonb,
    stone_options jsonb DEFAULT '[]'::jsonb,
    specs jsonb DEFAULT '{}'::jsonb,
    is_featured boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and grant all access
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.products FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.products FOR DELETE USING (true);


-- 3. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id text PRIMARY KEY,
    customer_name text NOT NULL,
    customer_email text NOT NULL,
    customer_phone text NOT NULL,
    address_line text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    pincode text NOT NULL,
    estimated_delivery text NOT NULL,
    courier_partner text NOT NULL,
    shipping_cost numeric NOT NULL,
    payment_method text NOT NULL,
    payment_status text NOT NULL,
    items jsonb DEFAULT '[]'::jsonb,
    total_amount numeric NOT NULL,
    status text NOT NULL,
    tracking_number text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and grant all access
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.orders FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.orders FOR DELETE USING (true);


-- 4. Inquiries Table
CREATE TABLE IF NOT EXISTS public.inquiries (
    id text PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    message text NOT NULL,
    order_id text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and grant all access
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select" ON public.inquiries FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.inquiries FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.inquiries FOR DELETE USING (true);


-- 5. Registered Users Table
CREATE TABLE IF NOT EXISTS public.registered_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text UNIQUE NOT NULL,
    phone text NOT NULL,
    address_line text,
    city text,
    state text,
    pincode text,
    password text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and grant all access
ALTER TABLE public.registered_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select" ON public.registered_users FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.registered_users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.registered_users FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.registered_users FOR DELETE USING (true);


-- 6. Product Reviews Table
CREATE TABLE IF NOT EXISTS public.product_reviews (
    id text PRIMARY KEY,
    product_id text REFERENCES public.products(id) ON DELETE CASCADE,
    user_name text NOT NULL,
    rating integer NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and grant all access
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select" ON public.product_reviews FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.product_reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.product_reviews FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.product_reviews FOR DELETE USING (true);
