-- Maa Diaries Jewelry E-Commerce Supabase Schema Setup Script
-- Copy and paste this script into your Supabase SQL Editor and click RUN.
--
-- SECURITY NOTES:
-- - Passwords are handled by Supabase Auth, NOT stored in registered_users.
-- - RLS policies enforce row-level access per table.
-- - Admin operations require auth.uid() to exist (Supabase Auth session).
-- - Public read for products, categories, coupons, site_settings, product_reviews.
-- - Customer data (orders, profile, inquiries) scoped to the owning user.
-- - Admin-only tables (email_logs, media_library) use a custom is_admin() check.

-- ============================================================
-- CLEAN UP OLD PERMISSIVE POLICIES (FROM ADMIN_INVENTORY / ADMIN_CONTENT)
-- ============================================================
DROP POLICY IF EXISTS "Allow public insert" ON public.coupons;
DROP POLICY IF EXISTS "Allow public update" ON public.coupons;
DROP POLICY IF EXISTS "Allow public delete" ON public.coupons;
DROP POLICY IF EXISTS "Allow public select" ON public.coupons;

DROP POLICY IF EXISTS "Allow public insert" ON public.site_settings;
DROP POLICY IF EXISTS "Allow public update" ON public.site_settings;
DROP POLICY IF EXISTS "Allow public delete" ON public.site_settings;
DROP POLICY IF EXISTS "Allow public select" ON public.site_settings;

DROP POLICY IF EXISTS "Allow public insert" ON public.media_library;
DROP POLICY IF EXISTS "Allow public update" ON public.media_library;
DROP POLICY IF EXISTS "Allow public delete" ON public.media_library;
DROP POLICY IF EXISTS "Allow public select" ON public.media_library;

DROP POLICY IF EXISTS "Allow public insert" ON public.email_logs;
DROP POLICY IF EXISTS "Allow public update" ON public.email_logs;
DROP POLICY IF EXISTS "Allow public delete" ON public.email_logs;
DROP POLICY IF EXISTS "Allow public select" ON public.email_logs;

DROP POLICY IF EXISTS "authenticated can manage site settings" ON public.site_settings;
DROP POLICY IF EXISTS "authenticated can manage coupons" ON public.coupons;
DROP POLICY IF EXISTS "public can read site settings" ON public.site_settings;
DROP POLICY IF EXISTS "public can read active coupons" ON public.coupons;

-- ============================================================
-- HELPER FUNCTION: is_admin()
-- Returns true if the current user's email matches the admin email.
-- Change the email below to your real admin account.
-- ============================================================
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT (auth.jwt() ->> 'email') = 'founder@maadiaries.com';
$$;


-- ============================================================
-- 1. CATEGORIES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
-- Public read, admin write
CREATE POLICY "categories_select_public" ON public.categories FOR SELECT USING (true);
CREATE POLICY "categories_insert_admin" ON public.categories FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "categories_update_admin" ON public.categories FOR UPDATE USING (public.is_admin());
CREATE POLICY "categories_delete_admin" ON public.categories FOR DELETE USING (public.is_admin());


-- ============================================================
-- 2. PRODUCTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.products (
    id text PRIMARY KEY,
    name text NOT NULL,
    description text,
    category text NOT NULL,
    subcategory text,
    price numeric NOT NULL,
    original_price numeric,
    discount numeric,
    image text,
    rating numeric DEFAULT 5.0,
    reviews_count integer DEFAULT 0,
    metal_options jsonb DEFAULT '[]'::jsonb,
    stone_options jsonb DEFAULT '[]'::jsonb,
    specs jsonb DEFAULT '{}'::jsonb,
    is_featured boolean DEFAULT false,
    stock integer DEFAULT 0,
    sku text,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
-- Public read, admin write
CREATE POLICY "products_select_public" ON public.products FOR SELECT USING (true);
CREATE POLICY "products_insert_admin" ON public.products FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "products_update_admin" ON public.products FOR UPDATE USING (public.is_admin());
CREATE POLICY "products_delete_admin" ON public.products FOR DELETE USING (public.is_admin());


-- ============================================================
-- 3. ORDERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.orders (
    id text PRIMARY KEY,
    customer_name text NOT NULL,
    customer_email text NOT NULL,
    customer_phone text NOT NULL,
    address_line text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    pincode text NOT NULL,
    estimated_delivery text NOT NULL,
    courier_partner text NOT NULL,
    shipping_cost numeric NOT NULL,
    payment_method text NOT NULL,
    payment_status text NOT NULL,
    items jsonb DEFAULT '[]'::jsonb,
    total_amount numeric NOT NULL,
    status text NOT NULL,
    tracking_number text,
    txnid text UNIQUE,
    payu_id text,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
-- Users can read their own orders (by email); admin can read all
CREATE POLICY "orders_select_own_or_admin" ON public.orders
  FOR SELECT USING (
    customer_email = (auth.jwt() ->> 'email')
    OR public.is_admin()
  );
-- Anyone authenticated can place an order (insert)
CREATE POLICY "orders_insert_authenticated" ON public.orders
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL OR public.is_admin());
-- Only admin can update order status, tracking, etc.
CREATE POLICY "orders_update_admin" ON public.orders
  FOR UPDATE USING (public.is_admin());
-- Only admin can delete orders
CREATE POLICY "orders_delete_admin" ON public.orders
  FOR DELETE USING (public.is_admin());


-- ============================================================
-- 4. INQUIRIES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.inquiries (
    id text PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    message text NOT NULL,
    order_id text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
-- Public can submit inquiries (contact form); admin can read all
CREATE POLICY "inquiries_insert_public" ON public.inquiries
  FOR INSERT WITH CHECK (true);
CREATE POLICY "inquiries_select_admin" ON public.inquiries
  FOR SELECT USING (public.is_admin());
-- Only admin can delete inquiries
CREATE POLICY "inquiries_delete_admin" ON public.inquiries
  FOR DELETE USING (public.is_admin());


-- ============================================================
-- 5. REGISTERED USERS TABLE (profile data only — NO passwords)
-- Passwords are managed by Supabase Auth (auth.users).
-- ============================================================
CREATE TABLE IF NOT EXISTS public.registered_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text UNIQUE NOT NULL,
    phone text NOT NULL,
    address_line text,
    city text,
    state text,
    pincode text,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.registered_users ENABLE ROW LEVEL SECURITY;
-- Users can read their own profile; admin can read all
CREATE POLICY "users_select_own_or_admin" ON public.registered_users
  FOR SELECT USING (
    email = (auth.jwt() ->> 'email')
    OR public.is_admin()
  );
-- Users can insert their own profile during registration
CREATE POLICY "users_insert_own" ON public.registered_users
  FOR INSERT WITH CHECK (
    email = (auth.jwt() ->> 'email')
    OR public.is_admin()
  );
-- Users can update their own profile
CREATE POLICY "users_update_own_or_admin" ON public.registered_users
  FOR UPDATE USING (
    email = (auth.jwt() ->> 'email')
    OR public.is_admin()
  );
-- Only admin can delete users
CREATE POLICY "users_delete_admin" ON public.registered_users
  FOR DELETE USING (public.is_admin());


-- ============================================================
-- 6. PRODUCT REVIEWS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.product_reviews (
    id text PRIMARY KEY,
    product_id text REFERENCES public.products(id) ON DELETE CASCADE,
    user_name text NOT NULL,
    rating integer NOT NULL,
    comment text NOT NULL,
    reply_comment text,
    replied_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
-- Public read; anyone authenticated can submit a review; admin can reply/delete
CREATE POLICY "reviews_select_public" ON public.product_reviews FOR SELECT USING (true);
CREATE POLICY "reviews_insert_authenticated" ON public.product_reviews
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL OR public.is_admin());
CREATE POLICY "reviews_update_admin" ON public.product_reviews
  FOR UPDATE USING (public.is_admin());
CREATE POLICY "reviews_delete_admin" ON public.product_reviews
  FOR DELETE USING (public.is_admin());


-- ============================================================
-- 7. COUPONS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.coupons (
    code text PRIMARY KEY,
    type text NOT NULL DEFAULT 'percent',
    value numeric NOT NULL,
    min_order numeric DEFAULT 0,
    active boolean DEFAULT true,
    description text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
-- Public read for active coupons; admin full write
CREATE POLICY "coupons_select_public" ON public.coupons FOR SELECT USING (true);
CREATE POLICY "coupons_insert_admin" ON public.coupons FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "coupons_update_admin" ON public.coupons FOR UPDATE USING (public.is_admin());
CREATE POLICY "coupons_delete_admin" ON public.coupons FOR DELETE USING (public.is_admin());


-- ============================================================
-- 8. SITE SETTINGS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.site_settings (
    id text PRIMARY KEY DEFAULT 'default',
    whatsapp text,
    support_phone text,
    support_email text,
    support_address text,
    free_shipping_threshold numeric DEFAULT 1000,
    seo_title text,
    seo_description text,
    hero_title text,
    hero_subtitle text,
    hero_description text,
    hero_image text,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    home_new_arrivals jsonb DEFAULT '[]'::jsonb,
    home_best_sellers jsonb DEFAULT '[]'::jsonb,
    home_trending jsonb DEFAULT '[]'::jsonb,
    instagram_feed_urls jsonb DEFAULT '[]'::jsonb,
    home_categories jsonb DEFAULT '[]'::jsonb
);

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
-- Public read; admin write
CREATE POLICY "settings_select_public" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "settings_insert_admin" ON public.site_settings FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "settings_update_admin" ON public.site_settings FOR UPDATE USING (public.is_admin());
CREATE POLICY "settings_delete_admin" ON public.site_settings FOR DELETE USING (public.is_admin());


-- ============================================================
-- 9. MEDIA LIBRARY TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.media_library (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL,
    name text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.media_library ENABLE ROW LEVEL SECURITY;
-- Admin only
CREATE POLICY "media_select_admin" ON public.media_library FOR SELECT USING (public.is_admin());
CREATE POLICY "media_insert_admin" ON public.media_library FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "media_delete_admin" ON public.media_library FOR DELETE USING (public.is_admin());


-- ============================================================
-- 10. EMAIL LOGS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.email_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email text NOT NULL,
    subject text NOT NULL,
    body text NOT NULL,
    status text NOT NULL DEFAULT 'sent',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.email_logs ENABLE ROW LEVEL SECURITY;
-- Admin only
CREATE POLICY "email_logs_select_admin" ON public.email_logs FOR SELECT USING (public.is_admin());
CREATE POLICY "email_logs_insert_admin" ON public.email_logs FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "email_logs_delete_admin" ON public.email_logs FOR DELETE USING (public.is_admin());


-- ============================================================
-- MIGRATION: Drop password column if it exists (from old schema)
-- Run this only if upgrading from the old schema that had passwords.
-- ============================================================
-- ALTER TABLE public.registered_users DROP COLUMN IF EXISTS password;

-- ============================================================
-- 11. INVENTORY STOCK DECREMENT TRIGGER
-- Automatically decrements product stock when an order is placed.
-- Runs with SECURITY DEFINER to bypass products table UPDATE RLS.
-- ============================================================
CREATE OR REPLACE FUNCTION public.decrement_stock_on_order()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  item jsonb;
  prod_id text;
  qty integer;
BEGIN
  -- Loop through each item in the order's items JSONB array
  FOR item IN SELECT * FROM jsonb_array_elements(NEW.items)
  LOOP
    prod_id := (item->'product'->>'id');
    qty := (item->>'quantity')::integer;
    
    -- Decrement stock if stock column is not null and stock > 0
    IF prod_id IS NOT NULL AND qty IS NOT NULL THEN
      UPDATE public.products
      SET stock = LEAST(GREATEST(0, stock - qty), stock)
      WHERE id = prod_id AND stock IS NOT NULL;
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_decrement_stock_on_order ON public.orders;

CREATE TRIGGER trg_decrement_stock_on_order
AFTER INSERT ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.decrement_stock_on_order();


-- ============================================================
-- 12. DATABASE INDEXES FOR PERFORMANCE
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON public.orders(customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.product_reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_coupons_code ON public.coupons(code);


-- ============================================================
-- 13. AUTOMATED UPDATED_AT TIMESTAMP TRIGGERS
-- ============================================================
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_orders_updated_at ON public.orders;
CREATE TRIGGER set_orders_updated_at
  BEFORE UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS set_products_updated_at ON public.products;
CREATE TRIGGER set_products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS set_users_updated_at ON public.registered_users;
CREATE TRIGGER set_users_updated_at
  BEFORE UPDATE ON public.registered_users
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
